Fixes #150 (Added meshery logo to the readme)
meshery/meshsync pull request #151
Opened 2022-09-30 20:02 UTC by UtkarshMishra12

Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
Added meshery logo to the readme

This PR fixes #150 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-10-05 06:50 UTC, legendarykamal requested changes
Changes needed.

2022-10-05 06:50 UTC, legendarykamal commented on README.md
> +  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-dark-text-side.svg"  width="70%" align="cent
please do not use meshery/meshery 's logo, store it locally( if meshsync doesn't have it ) and then use relative referencing to get it.

2022-10-05 06:50 UTC, legendarykamal commented on README.md
> +  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-light-text-side.svg" width="70%" align="cen
here too.

2022-10-05 06:53 UTC, UtkarshMishra12 commented on README.md
> +  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-light-text-side.svg" width="70%" align="cen
On it @legendarykamal

2022-10-13 19:40 UTC, UtkarshMishra12 commented
@legendarykamal As per your suggestion, I have stored the logos locally and then used relative referencing to render them.
Let me know your thought on it.

2022-10-13 20:15 UTC, UtkarshMishra12 commented
@legendarykamal I'm closing this PR because of some error on my side and will be opening a new PR for the issue.

2022-10-13 20:15 UTC, closed without merging