docs: issue #210 Issue Template Updates for Figma link
meshery/meshsync pull request #212
Opened 2023-07-13 07:31 UTC by aryanas159

**Description**

This PR fixes #
Issue #210
**Notes for Reviewers**
I have copied the given information in the docs. I am happy to make any changes if required.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-13 12:57 UTC, leecalcote requested changes

2023-07-13 12:57 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/ci.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)```
remove backticks, please.

2023-07-13 12:57 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)```
remove backticks

2023-07-13 12:57 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- - 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)``
same here.

2023-07-15 07:40 UTC, aryanas159 commented
@leecalcote Hey! I have made the necessary changes, can you please review.

2023-07-16 05:37 UTC, leecalcote commented
@yashchaddha, would you like to offer review?

2023-07-16 08:56 UTC, yashchaddha commented
Yes @leecalcote

2023-07-16 14:53 UTC, leecalcote commented
@yashchaddha and how does it look?

2023-07-16 21:22 UTC, yashchaddha commented
Hi @leecalcote apologies for responding late, I was under the impression that I would be assigned as reviewer and then I should start. However I  have reviewed the above PR and looks good to me.

I wanted to confirm that this line has been added extra in bug_report.md and feature_request.md file. Is that fine? or shall we discard that because there will be two references to Meshery UI links, thus increasing redundancy.

Also @aryanas159  I would want you to squash your commits into one while opening a PR

Thankyou

2023-07-16 21:26 UTC, yashchaddha commented on .github/ISSUE_TEMPLATE/feature_request.md
There is one "-" extra in line 22

- - 🎨 Wireframes

2023-07-16 21:26 UTC, yashchaddha commented on .github/ISSUE_TEMPLATE/bug_report.md
39th Line is added Extra, while could not find the same in Master branch. Kindly confirm with @leecalcote on this as the issue was to originally replace the Figma references

2023-07-16 21:26 UTC, yashchaddha commented on .github/ISSUE_TEMPLATE/feature_request.md
22nd Line is added Extra, while could not find the same in Master branch. Kindly confirm with @leecalcote on this as the issue was to originally replace the Figma references

2023-07-17 04:51 UTC, aryanas159 commented on .github/ISSUE_TEMPLATE/feature_request.md
@yashchaddha I was confused about this  too.

2023-07-17 04:53 UTC, aryanas159 commented
@leecalcote  Should I replace 
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

this description with 

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

or these are two different lines.

2023-07-17 20:47 UTC, leecalcote commented
@yashchaddha guidance?

2023-07-18 02:15 UTC, yashchaddha commented
Hi @aryanas159  The main idea is to replace the Figma references with the open invite link, hence instead of adding another line in feature_request and bug_report.md, Kindly replace the line 

- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

with

- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.


Thankyou

2023-07-18 04:34 UTC, aryanas159 commented
@yashchaddha I have made the required changes

2023-07-18 04:36 UTC, yashchaddha commented
Lgtm, @aryanas159 can you squash these commits in one?

2023-07-18 04:50 UTC, aryanas159 commented
> Lgtm, @aryanas159 can you squash these commits in one?

@yashchaddha Done

2023-07-18 05:12 UTC, yashchaddha commented
Hi @leecalcote this PR looks good to me and can be merged 

Thankyou

2023-07-18 18:18 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). F
```suggestion
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.
```

2023-07-18 18:18 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/ci.md
>  - 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
```suggestion
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)
```

2023-07-18 18:18 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). F
```suggestion
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.
```

2023-07-18 18:19 UTC, merged